version: '2'
services:
  eurekaserver:
     image:   citadel/tmx-eureka-service:v2
     ports:
       - "8761:8761"
  addressservice:
      image: citadel/tmx-address-service:v2
      ports:
        - "8085:8085"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8085"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT:   "8761"
        ENCRYPT_KEY:       "IMSYMMETRIC"
  pupilservice:
      image: citadel/tmx-pupil-service:v2
      ports:
        - "8086:8086"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8086"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT:   "8761"
        ENCRYPT_KEY:       "IMSYMMETRIC"